name: apidocs
on: 
  push:
    branches: 
      - main

jobs:
  apidocs:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install tox

    - name: Generate API documentation
      run: |

        tox -e apidocs

    - name: Push API documentation to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate API documentation"
